@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package xyz.immortius.chunkbychunk.interop;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;